### ISSUE TITLE
Compilation fail

### ISSUE THREAD

**Issue by espritlibre** [matrix-org/matrix-ircd#17]
Hello

Thanks for this project, it is for me the perfect usage for matrix and my phone (sailfishOs with no app but an irc application.)

But when I try to run cargo I have fail and can't run the program

OS : Debian SID
Cargo : cargo 0.13.0-nightly (109cb7c 2016-08-19)
And result of Cargo run is

>    Compiling serde_codegen v0.8.12
>    Compiling slog-term v1.1.0
> error[E0554]: #[feature] may not be used on the stable release channel
>  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_codegen-0.8.12/src/lib.rs:5:43
>   |
> 5 | #![cfg_attr(not(feature = "with-syntex"), feature(rustc_private, plugin))]
>   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to previous error

I try to use serde_codegen v0.8.11 but compilation failed too.

Any idea ?

Thanks

**Comment by erikjohnston** [comment]
> #[feature] may not be used on the stable release channel

Generally implies that you're not using a nightly compiler. How did you install rust? And what is the output of `rustc --version` (run in the same folder as ircd)?

**Comment by espritlibre** [comment]
OK, I just found how to install nighty version for rustc.

Thanks it's better when I RFTM

I used that 'curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly' and not the debian package. Now compilation is OK.

Let's go for testing.
