### ISSUE TITLE
Wrong media URLs  shown

### ISSUE THREAD

**Issue by madduck** [matrix-org/matrix-ircd#41]
I just noticed that while Riot showed me a screenshot in a room, which had the URL (not the thumbnail URL, but the one of the actual image)

    https://matrix.madduck.net/_matrix/media/v1/download/gruenhage.xyz/wPginFhvkMwSxTGvQIMpaJsV

this was displayed in the IRC channel seen through `matrix-ircd` as:

    https://matrix.madduck.net//media/r0/download/gruenhage.xyz/wPginFhvkMwSxTGvQIMpaJsV

which is a 404. There are two differences:

- `_matrix` is missing in the first path component;
- `r0` is used instead of `v1`in the 3rd path component.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/matrix-ircd/commit/cac14b6ba329c5e54311b4e6ea07fd165a68d0e5 should fix this
