### ISSUE TITLE
Clarify what this project is about

### ISSUE THREAD

**Issue by rubo77** [matrix-org/matrix-ircd#56]
Please add a sentence in the readme, what this tool is doing.

Is this an alternative for https://github.com/matrix-org/matrix-appservice-irc?

If not, what is the difference?

What is the difference to a usual IRCd?

**Comment by t3chguy** [comment]
This is the inverse of matrix-appservice-irc almost.

With this project you connect to *it* with any standard IRC Client and then *it* connects to a Matrix server, letting you use an IRC Client to communicate with Matrix, whereas matrix-appservice-irc is primarily a way to use a Matrix client to communicate with IRC (though with it existing at the server level it goes both ways)

**Comment by rubo77** [comment]
Ah ok, you should add that sentence to the README.md

**Comment by jplatte** [comment]
PRs to improve the readme would be welcome! :)

**Comment by rubo77** [comment]
> (though with it existing at the server level it goes both ways)

I created a PR, but what do you mean by this sentence?
